import Head from 'next/head';
import Hero from '@/components/Hero';
import Expertise from '@/components/Expertise';
import Work from '@/components/Work';
import Contact from '@/components/Contact';
import About from '@/components/About';
import { Element } from 'react-scroll';
export default function Home() {
	return (
		<>
			<Head>
				<title>iamdineshbasnet</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Element name="home">
					<Hero />
				</Element>
				<Element name="about">
					<About />
				</Element>
				<Element name="expertise">
					<Expertise />
				</Element>
				<Element name="work">
					<Work />
				</Element>
				<Element name="contact">
					<Contact />
				</Element>
			</main>
		</>
	);
}
