import Head from 'next/head'
import Hero from '@/components/Hero'
import Expertise from '@/components/Expertise'
import Work from '@/components/Work'
import Contact from '@/components/Contact'
export default function Home() {
  return (
    <>
      <Head>
        <title>iamdineshbasnet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <main>
        <Hero />

        <Expertise/>

        <Work />

        <Contact />
     </main>
    </>
  )
}
